image: l.gcr.io/google/bazel:latest

pipelines:
  branches:
    "**":
      - parallel:
          - step:
              caches: &caches
                - bazel-repo
                - bazel-disk
              script:
                - cd 1-up-and-running
                - ./exercise.sh
          - step:
              caches: *caches
              script:
                - cd 2-java-tooling
                - ./exercise.sh
          - step:
              caches: *caches
              script:
                - cd 3-java-dependencies
                - ./exercise.sh
          - step:
              caches: *caches
              script:
                - cd 4-multi-language
                - ./exercise.sh
          - step:
              caches: *caches
              script:
                - cd 5-full-stack-suite
                - ./exercise.sh

definitions:
  caches:
    bazel-repo: $HOME/.cache/bazel-repo
    bazel-disk: $HOME/.cache/bazel-disk
